### PR TITLE
remove logs in  for settled or cancelled invoice

### LINKED ISSUE #85: Remove logs in `failInvoice` for settled or cancelled invoice
Currently, even if an invoice is settled, we will still display the log:

`logger.Debugw("Invoice to fail no longer open/accepted")` 

because the invoice is still in `autoReleaseHeap`.

It could be good to remove it from `autoReleaseHeap` or to change the log.

### PR DESCRIPTION
**Pull request by Torakushi**
close #85

### CODE REVIEW

**Review by aakselrod-nydig — APPROVED** [review]
LGTM!

File: invoiceregistry.go [hunk 1]
```diff
@@ -489,8 +489,7 @@ func (i *InvoiceRegistry) failInvoice(hash lntypes.Hash) error {
 	// Retrieve invoice.
 	set, ok := i.sets.get(hash)
 	if !ok {
-		logger.Debugw("Invoice to fail no longer open/accepted")
-
+		// Invoice has already been settled or cancelled
```
Comment (joostjager) [inline invoiceregistry.go:492]: Could add in comment that we don't log because this is lazy clean up.

**Review by joostjager — APPROVED** [review]
