### PR TITLE
Enable race detection in CI, fix a data race

### LINKED ISSUE #64: Run tests in CI with race detection enabled
We may have some data races, so we should run our tests to be able to detect them automatically so we can fix them. This should include fixing any races detected after first enabling it.

### PR DESCRIPTION
**Pull request by aakselrod-nydig**
This PR enables race detection when running tests in CI. It also fixes a data race in the database migration discovery process, found automatically when running tests.

Fixes #64

### CODE REVIEW

File: persistence/migrations/migrations.go [hunk 1]
```diff
@@ -15,9 +19,17 @@ func init() {
 
 // DiscoverSQLMigrations scans dir for migrations.
 func DiscoverSQLMigrations(dir string) error {
+	sqlDiscoveryMtx.Lock()
+	defer sqlDiscoveryMtx.Unlock()
+
+	if sqlDiscovered {
+		return nil
```
Comment (joostjager) [inline persistence/migrations/migrations.go]: I think this can be done in a more compact way using `sync.Once`

File: persistence/migrations/migrations.go [hunk 2]
```diff
@@ -1,9 +1,13 @@
...
 
 import (
+	"sync"
+
 	"github.com/go-pg/migrations/v8"
 )
 
+var sqlDiscoveryMtx sync.Mutex
+
 var Collection = migrations.NewCollection()
```
Comment (Torakushi) [inline persistence/migrations/migrations.go]: That's nothing but use
var (

)

To group these declarations

File: persistence/migrations/migrations.go (hunk 1 above)
Comment (aakselrod-nydig) [reply persistence/migrations/migrations.go]: I've updated it using `sync.Once`, it's quite a bit more compact. Thanks!

File: persistence/migrations/migrations.go (hunk 2 above)
Comment (aakselrod-nydig) [reply persistence/migrations/migrations.go]: I've added the grouping syntax, but reduced the number of variables here back to 2. Should I still group, and should I keep an empty line between the two variable declarations?

Comment (Torakushi) [reply persistence/migrations/migrations.go]: Looks good (that was only a little note!)

**Review by Torakushi — APPROVED** [review]
LGTM

**Review by joostjager — APPROVED** [review]
