### PR TITLE
invoice without description should be allowed

### LINKED ISSUE #55: Invoices without 'Description' should be allowed
When creating an invoice, if 'Description' is empty and 'DescriptionHash' is nil, `zpay32` returns an error:

`neither description nor description hash set`

Invoice should be allowed even without 'Description'.

In that case, simply add an empty string for Description  (`options = append(options, zpay32.Description(""))` )

### PR DESCRIPTION
**Pull request by Torakushi**
close #55

### CODE REVIEW

**Review by joostjager — APPROVED** [review]

File: invoice_creator.go [hunk 1]
```diff
@@ -137,17 +137,19 @@ func (c *InvoiceCreator) Create(amtMSat int64, expiry time.Duration,
 
 	options = append(options, zpay32.Expiry(expiry))
 
+	if descHash != nil {
```
Comment (joostjager) [inline invoice_creator.go]: Moving this up wasn't really necessary I think?

Comment (Torakushi) [reply invoice_creator.go]: No indeed, I changed my way of doing things along the way.

it's a vestige
